// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exwuyjdhfiqnhdpmrzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4d3V5amRoZmlxbmhkcG1yemZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDYyNjAsImV4cCI6MjA2MTkyMjI2MH0.HEARhZnlYLZnY1mS63S0kAD7s7HIXME7sV8fXnrAf1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);